---

- name: Example
  hosts: ubuntu
  become: true
  vars:
    user_name: "padella"
    user_comment: "from playbook vars"
    user_shell: /bin/bash
    user_uid: "7777"
  # vars_files:
  # - vars.yaml
  tasks:
    # Docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    # - name: "Create a user"
    #   user:
    #     name: "padella"
    #     comment: "hard coding"
    #     shell: "/bin/bash"
    #     uid: "7777"
    - name: "Create a user"
      user:
        name: "{{ user_name }}"
        comment: "{{ user_comment }}"
        shell: "{{ user_shell }}"
        uid: "{{ user_uid }}"
