---

- name: Example
  hosts: all
  become: true
  vars:
    users:
      - name: john
        shell: /bin/bash
        enabled: true
      - name: alice
        shell: /bin/sh
        enabled: false
      - name: claud
        shell: /bin/bash
        enabled: true
      - name: henry
        shell: /bin/sh
        enabled: false
      - name: jeremy
        shell: /bin/bash
        enabled: true
      - name: may
        shell: /bin/sh
        enabled: false
  tasks:
    # Docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    - name: "Create a user if enabled in Amazon Linux"
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        comment: "FastCampus DevOps"
        state: "present"
      loop: "{{ users }}"
      when: item.enabled and (ansible_facts["distribution"] == "Amazon") # ansible_facts["describution"] 은 운영체제 배포판 종류를 의미
