---
- name: "Initialize instance for ansible"
  hosts: default
  become: true

  tasks:
  - name: "Install pip"
    apt:
      name:
      - "python3-pip"
      - "python3-setuptools"
      state: present
      update_cache: yes

  - name: "Install Dependencies"
    pip:
      name:
      - "virtualenv"

  - name: "Install Ansible"
    pip:
      name: ansible
      # default(omit) 문법
      # 변수가 선언되지 않은 경우 module 의 parameter 자체를 무시
      # Docs: https://blog.leocat.kr/notes/2018/02/11/ansible-default-value
      version: "{{ ansible_install_version | default(omit) }}"
